version: '3.7'

services:
  laravel.test:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
      APP_ENV: local
      APP_DEBUG: 'true'
      APP_KEY: base64:YOUR_APP_KEY_HERE
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: your_database
      DB_USERNAME: your_username
      DB_PASSWORD: your_password
      REDIS_HOST: redis
      QUEUE_CONNECTION: redis
    volumes:
      - '.:/var/www/html'
    depends_on:
      - postgres
      - redis
      - meilisearch
      - mailpit
      - selenium

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: your_database
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
    volumes:
      - 'sail-postgres:/var/lib/postgresql/data'
    networks:
      - sail

  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'sail-redis:/data'
    networks:
      - sail

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '7700:7700'
    volumes:
      - 'sail-meilisearch:/meili_data'
    networks:
      - sail

  mailpit:
    image: 'axllent/mailpit:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - sail

  selenium:
    image: selenium/standalone-chrome
    volumes:
      - '/dev/shm:/dev/shm'
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-postgres:
    driver: local
  sail-redis:
    driver: local
  sail-meilisearch:
    driver: local
